#!/bin/bash

set -eu

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [ "$#" -ne 1 ]; then
  echo -e "${RED}Expected name of role as argument${NC}"
  exit 1
fi
ROLE_NAME=${1}

CHEF_OPTS=${CHEF_OPTS:-}
CHEF_DEBUG=${CHEF_DEBUG:-}
if [ "${CHEF_DEBUG}" == true ]; then
  CHEF_OPTS="${CHEF_OPTS} -l debug"
fi

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd ${MY_DIR}

  ROLE_FILE=roles/${ROLE_NAME}.json
  if [ ! -e ${ROLE_FILE} ]; then
    echo -e "${RED}Role file ${ROLE_FILE} does not exist${NC}"
    exit 1
  fi

  echo -e "Preparing workstation..."
  sudo chef-client \
    --local-mode \
    -c config/solo.rb \
    -j roles/${ROLE_NAME}.json \
    ${CHEF_OPTS}
popd

echo -e "${GREEN}Successfully prepared workstation with role as ${ROLE_NAME}${NC}"
